//
// Auto-generated asset header - DO NOT EDIT MANUALLY
// Generated by NoZ Game Engine Asset Importer
//

// @fonts
// LoadedAssets.fonts.roboto_black
//
// @shaders
// LoadedAssets.shaders._default
// LoadedAssets.shaders.text
// LoadedAssets.shaders.ui
// LoadedAssets.shaders.vfx
//
// @stylesheets
// LoadedAssets.ui.mesh_editor
// LoadedAssets.ui.notifications
//
// @textures
// LoadedAssets.textures.palette
//

#pragma once

#include <noz/core_assets.h>

// Forward declarations
struct Allocator;
struct Shader;
struct Vfx;
struct Texture;
struct Mesh;
struct Font;
struct Material;
struct Skeleton;
struct Sound;

struct LoadedAssets
{
    struct
    {
        Font* roboto_black;
    } fonts;
    struct
    {
        Shader* _default;
        Shader* text;
        Shader* ui;
        Shader* vfx;
    } shaders;
    struct
    {
        Texture* palette;
    } textures;
    struct
    {
        StyleSheet* mesh_editor;
        StyleSheet* notifications;
    } ui;
};

extern LoadedAssets Assets;
extern LoadedCoreAssets g_core_assets;

bool LoadAssets(Allocator* allocator);
void UnloadAssets();

#ifdef NOZ_EDITOR
void HotloadAsset(const Name* incoming_name);
#endif
