//
// Auto-generated asset header - DO NOT EDIT MANUALLY
// Generated by NoZ Game Engine Asset Importer
//

#pragma once

#include <noz/core_assets.h>

// @Font
extern Font* FONT_SEGUISB;

// @Shader
extern Shader* SHADER_VFX;
extern Shader* SHADER_UI;
extern Shader* SHADER_TEXT;
extern Shader* SHADER_LIT;

// @Style
extern StyleSheet* STYLESHEET_VIEW;
extern StyleSheet* STYLESHEET_NOTIFICATIONS;
extern StyleSheet* STYLESHEET_MESH_EDITOR;
extern StyleSheet* STYLESHEET_COMMAND_PALETTE;

// @Texture
extern Texture* TEXTURE_PALETTE;

// @name
extern const Name* NAME_COLOR_PICKER_IMAGE;
extern const Name* NAME_COMMAND_PALETTE;
extern const Name* NAME_COMMAND_INPUT;
extern const Name* NAME_COMMAND_COLON;
extern const Name* NAME_COMMAND_TEXT;
extern const Name* NAME_COMMAND_TEXT_CURSOR;
extern const Name* NAME_COMMAND_TEXT_PREVIEW;
extern const Name* NAME_ASSET_NAME_CONTAINER;
extern const Name* NAME_ASSET_NAME;
extern const Name* NAME_NOTIFICATION_CONTAINER;
extern const Name* NAME_NOTIFICATION;
extern const Name* NAME_NOTIFICATION_TEXT;
extern const Name* NAME_A;
extern const Name* NAME_E;
extern const Name* NAME_M;
extern const Name* NAME_R;
extern const Name* NAME_NEW;
extern const Name* NAME_N;
extern const Name* NAME_EDIT;
extern const Name* NAME_S;
extern const Name* NAME_RENAME;
extern const Name* NAME_SAVE;
extern const Name* NAME_MESH;
extern const Name* NAME_SKELETON;
extern const Name* NAME_ANIMATION;



extern bool LoadAssets(Allocator* allocator);
extern void UnloadAssets();

#ifdef NOZ_EDITOR
extern void HotloadAsset(const Name* incoming_name);
#endif
