//
// Auto-generated asset header - DO NOT EDIT MANUALLY
// Generated by NoZ Game Engine Asset Importer
//

#pragma once

#include <noz/core_assets.h>

// @Font
extern Font* FONT_SEGUISB;

// @Mesh
extern Mesh* MESH_SHADER;

// @Shader
extern Shader* SHADER_VFX;
extern Shader* SHADER_UI_VIGNETTE;
extern Shader* SHADER_UI;
extern Shader* SHADER_TEXT;
extern Shader* SHADER_LIT;
extern Shader* SHADER_SOLID;

// @Texture
extern Texture* TEXTURE_EDITOR_PALETTE;

// @name
extern const Name* NAME_TEXT;
extern const Name* NAME_CONTAINER;
extern const Name* NAME_INPUT;
extern const Name* NAME_INPUT_SMALL;
extern const Name* NAME_COLON;
extern const Name* NAME_CURSOR;
extern const Name* NAME_PREVIEW;
extern const Name* NAME_COLORS;
extern const Name* NAME_COLOR_IMAGE;
extern const Name* NAME_SELECTED_COLOR;
extern const Name* NAME_ITEM;
extern const Name* NAME_ITEM_TEXT;
extern const Name* NAME_ASSET_NAME_CONTAINER;
extern const Name* NAME_ASSET_NAME;
extern const Name* NAME_A;
extern const Name* NAME_E;
extern const Name* NAME_M;
extern const Name* NAME_R;
extern const Name* NAME_NEW;
extern const Name* NAME_N;
extern const Name* NAME_EDIT;
extern const Name* NAME_S;
extern const Name* NAME_RENAME;
extern const Name* NAME_SAVE;
extern const Name* NAME_MESH;
extern const Name* NAME_SKELETON;
extern const Name* NAME_ANIMATION;

extern bool LoadAssets(Allocator* allocator);
extern void UnloadAssets();

#ifdef NOZ_EDITOR
extern void HotloadAsset(const Name* incoming_name, AssetSignature incoming_signature);
#endif
