//
// Auto-generated asset header - DO NOT EDIT MANUALLY
// Generated by NoZ Game Engine Asset Importer
//

#pragma once

#include <noz/core_assets.h>

// @Font
extern Font* FONT_SEGUISB;

// @Shader
extern Shader* SHADER_VFX;
extern Shader* SHADER_UI_VIGNETTE;
extern Shader* SHADER_UI;
extern Shader* SHADER_TEXT;
extern Shader* SHADER_SOLID;
extern Shader* SHADER_LIT;

// @StyleSheet
extern StyleSheet* STYLESHEET_VIEW;
extern StyleSheet* STYLESHEET_NOTIFICATIONS;
extern StyleSheet* STYLESHEET_MESH_EDITOR;
extern StyleSheet* STYLESHEET_COMMAND_PALETTE;

// @Texture
extern Texture* TEXTURE_SOLID_PALETTE;
extern Texture* TEXTURE_PALETTE;

// @name
extern const Name* NAME_COLORS;
extern const Name* NAME_ASSET_NAME_CONTAINER;
extern const Name* NAME_ASSET_NAME;
extern const Name* NAME_CONTAINER;
extern const Name* NAME_ITEM;
extern const Name* NAME_ITEM_TEXT;
extern const Name* NAME_INPUT;
extern const Name* NAME_INPUT_SMALL;
extern const Name* NAME_COLON;
extern const Name* NAME_TEXT;
extern const Name* NAME_CURSOR;
extern const Name* NAME_PREVIEW;
extern const Name* NAME_A;
extern const Name* NAME_E;
extern const Name* NAME_M;
extern const Name* NAME_R;
extern const Name* NAME_NEW;
extern const Name* NAME_N;
extern const Name* NAME_EDIT;
extern const Name* NAME_S;
extern const Name* NAME_RENAME;
extern const Name* NAME_SAVE;
extern const Name* NAME_MESH;
extern const Name* NAME_SKELETON;
extern const Name* NAME_ANIMATION;

// @STYLE_VIEW
constexpr StyleId STYLE_VIEW_ASSET_NAME_CONTAINER = {0,0};
constexpr StyleId STYLE_VIEW_ASSET_NAME = {0,1};

// @STYLE_NOTIFICATIONS
constexpr StyleId STYLE_NOTIFICATIONS_CONTAINER = {1,0};
constexpr StyleId STYLE_NOTIFICATIONS_ITEM = {1,1};
constexpr StyleId STYLE_NOTIFICATIONS_ITEM_TEXT = {1,2};

// @STYLE_MESH_EDITOR
constexpr StyleId STYLE_MESH_EDITOR_COLORS = {2,0};

// @STYLE_COMMAND_PALETTE
constexpr StyleId STYLE_COMMAND_PALETTE_CONTAINER = {3,0};
constexpr StyleId STYLE_COMMAND_PALETTE_INPUT = {3,1};
constexpr StyleId STYLE_COMMAND_PALETTE_INPUT_SMALL = {3,2};
constexpr StyleId STYLE_COMMAND_PALETTE_COLON = {3,3};
constexpr StyleId STYLE_COMMAND_PALETTE_TEXT = {3,4};
constexpr StyleId STYLE_COMMAND_PALETTE_CURSOR = {3,5};
constexpr StyleId STYLE_COMMAND_PALETTE_PREVIEW = {3,6};


extern bool LoadAssets(Allocator* allocator);
extern void UnloadAssets();

#ifdef NOZ_EDITOR
extern void HotloadAsset(const Name* incoming_name);
#endif
