//
// Auto-generated asset header - DO NOT EDIT MANUALLY
// Generated by NoZ Game Engine Asset Importer
//

#include <noz/noz.h>
#include "nozed_assets.h"

#ifdef NDEBUG
#include "nozed_assets_build.cpp"
#endif

// @Mesh
Mesh* MESH_UI_ICON_ROOT_MOTION_OFF = nullptr;
Mesh* MESH_UI_ICON_ROOT_MOTION = nullptr;
Mesh* MESH_ASSET_ICON_VFX = nullptr;
Mesh* MESH_ASSET_ICON_SOUND = nullptr;
Mesh* MESH_ASSET_ICON_SHADER = nullptr;
Mesh* MESH_ASSET_ICON_FONT = nullptr;

// @Texture
Texture* TEXTURE_PALETTE = nullptr;

// @Font
Font* FONT_SEGUISB = nullptr;

// @Shader
Shader* SHADER_VFX = nullptr;
Shader* SHADER_UI_VIGNETTE = nullptr;
Shader* SHADER_UI = nullptr;
Shader* SHADER_TEXT = nullptr;
Shader* SHADER_LIT = nullptr;
Shader* SHADER_SOLID = nullptr;

// @name
const Name* NAME_VFX = nullptr;
const Name* NAME_A = nullptr;
const Name* NAME_E = nullptr;
const Name* NAME_M = nullptr;
const Name* NAME_B = nullptr;
const Name* NAME_R = nullptr;
const Name* NAME_NEW = nullptr;
const Name* NAME_EDIT = nullptr;
const Name* NAME_N = nullptr;
const Name* NAME_S = nullptr;
const Name* NAME_BUILD = nullptr;
const Name* NAME_AM = nullptr;
const Name* NAME_RENAME = nullptr;
const Name* NAME_SAVE = nullptr;
const Name* NAME_MESH = nullptr;
const Name* NAME_SKELETON = nullptr;
const Name* NAME_ANIMATION = nullptr;
const Name* NAME_ANIMATEDMESH = nullptr;
const Name* NAME_RU = nullptr;
const Name* NAME_MIRROR = nullptr;

// @path
const Name* PATH_SHADER_VFX = nullptr;
const Name* PATH_SHADER_UI_VIGNETTE = nullptr;
const Name* PATH_SHADER_UI = nullptr;
const Name* PATH_SHADER_TEXT = nullptr;
const Name* PATH_SHADER_LIT = nullptr;
const Name* PATH_TEXTURE_PALETTE = nullptr;
const Name* PATH_SHADER_SOLID = nullptr;
const Name* PATH_MESH_UI_ICON_ROOT_MOTION_OFF = nullptr;
const Name* PATH_MESH_UI_ICON_ROOT_MOTION = nullptr;
const Name* PATH_MESH_ASSET_ICON_VFX = nullptr;
const Name* PATH_MESH_ASSET_ICON_SOUND = nullptr;
const Name* PATH_MESH_ASSET_ICON_SHADER = nullptr;
const Name* PATH_MESH_ASSET_ICON_FONT = nullptr;
const Name* PATH_FONT_SEGUISB = nullptr;

// @load
bool LoadAssets(Allocator* allocator)
{
    // @name
    NAME_VFX = GetName("vfx");
    NAME_A = GetName("a");
    NAME_E = GetName("e");
    NAME_M = GetName("m");
    NAME_B = GetName("b");
    NAME_R = GetName("r");
    NAME_NEW = GetName("new");
    NAME_EDIT = GetName("edit");
    NAME_N = GetName("n");
    NAME_S = GetName("s");
    NAME_BUILD = GetName("build");
    NAME_AM = GetName("am");
    NAME_RENAME = GetName("rename");
    NAME_SAVE = GetName("save");
    NAME_MESH = GetName("mesh");
    NAME_SKELETON = GetName("skeleton");
    NAME_ANIMATION = GetName("animation");
    NAME_ANIMATEDMESH = GetName("animatedmesh");
    NAME_RU = GetName("ru");
    NAME_MIRROR = GetName("mirror");

    // @path
    PATH_SHADER_VFX = GetName("vfx");
    PATH_SHADER_UI_VIGNETTE = GetName("ui_vignette");
    PATH_SHADER_UI = GetName("ui");
    PATH_SHADER_TEXT = GetName("text");
    PATH_SHADER_LIT = GetName("lit");
    PATH_TEXTURE_PALETTE = GetName("palette");
    PATH_SHADER_SOLID = GetName("solid");
    PATH_MESH_UI_ICON_ROOT_MOTION_OFF = GetName("ui_icon_root_motion_off");
    PATH_MESH_UI_ICON_ROOT_MOTION = GetName("ui_icon_root_motion");
    PATH_MESH_ASSET_ICON_VFX = GetName("asset_icon_vfx");
    PATH_MESH_ASSET_ICON_SOUND = GetName("asset_icon_sound");
    PATH_MESH_ASSET_ICON_SHADER = GetName("asset_icon_shader");
    PATH_MESH_ASSET_ICON_FONT = GetName("asset_icon_font");
    PATH_FONT_SEGUISB = GetName("seguisb");

    // @Mesh
    NOZ_LOAD_MESH(allocator, PATH_MESH_UI_ICON_ROOT_MOTION_OFF, MESH_UI_ICON_ROOT_MOTION_OFF);
    NOZ_LOAD_MESH(allocator, PATH_MESH_UI_ICON_ROOT_MOTION, MESH_UI_ICON_ROOT_MOTION);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ASSET_ICON_VFX, MESH_ASSET_ICON_VFX);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ASSET_ICON_SOUND, MESH_ASSET_ICON_SOUND);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ASSET_ICON_SHADER, MESH_ASSET_ICON_SHADER);
    NOZ_LOAD_MESH(allocator, PATH_MESH_ASSET_ICON_FONT, MESH_ASSET_ICON_FONT);

    static Mesh* _MESH[] = {
        MESH_UI_ICON_ROOT_MOTION_OFF,
        MESH_UI_ICON_ROOT_MOTION,
        MESH_ASSET_ICON_VFX,
        MESH_ASSET_ICON_SOUND,
        MESH_ASSET_ICON_SHADER,
        MESH_ASSET_ICON_FONT,
        nullptr
    };

    MESH = _MESH;

    // @Texture
    NOZ_LOAD_TEXTURE(allocator, PATH_TEXTURE_PALETTE, TEXTURE_PALETTE);

    static Texture* _TEXTURE[] = {
        TEXTURE_PALETTE,
        nullptr
    };

    TEXTURE = _TEXTURE;

    // @Font
    NOZ_LOAD_FONT(allocator, PATH_FONT_SEGUISB, FONT_SEGUISB);

    static Font* _FONT[] = {
        FONT_SEGUISB,
        nullptr
    };

    FONT = _FONT;

    // @Shader
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_VFX, SHADER_VFX);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_UI_VIGNETTE, SHADER_UI_VIGNETTE);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_UI, SHADER_UI);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_TEXT, SHADER_TEXT);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_LIT, SHADER_LIT);
    NOZ_LOAD_SHADER(allocator, PATH_SHADER_SOLID, SHADER_SOLID);

    static Shader* _SHADER[] = {
        SHADER_VFX,
        SHADER_UI_VIGNETTE,
        SHADER_UI,
        SHADER_TEXT,
        SHADER_LIT,
        SHADER_SOLID,
        nullptr
    };

    SHADER = _SHADER;

    return true;
}

// @unload
void UnloadAssets()
{
    // @Mesh
    Free(MESH_UI_ICON_ROOT_MOTION_OFF);
    Free(MESH_UI_ICON_ROOT_MOTION);
    Free(MESH_ASSET_ICON_VFX);
    Free(MESH_ASSET_ICON_SOUND);
    Free(MESH_ASSET_ICON_SHADER);
    Free(MESH_ASSET_ICON_FONT);

    // @Texture
    Free(TEXTURE_PALETTE);

    // @Font
    Free(FONT_SEGUISB);

    // @Shader
    Free(SHADER_VFX);
    Free(SHADER_UI_VIGNETTE);
    Free(SHADER_UI);
    Free(SHADER_TEXT);
    Free(SHADER_LIT);
    Free(SHADER_SOLID);
}

#ifdef NOZ_EDITOR

void HotloadAsset(const Name* incoming_name, AssetType incoming_type)
{
    // @Mesh
    NOZ_RELOAD_MESH(PATH_MESH_UI_ICON_ROOT_MOTION_OFF, MESH_UI_ICON_ROOT_MOTION_OFF);
    NOZ_RELOAD_MESH(PATH_MESH_UI_ICON_ROOT_MOTION, MESH_UI_ICON_ROOT_MOTION);
    NOZ_RELOAD_MESH(PATH_MESH_ASSET_ICON_VFX, MESH_ASSET_ICON_VFX);
    NOZ_RELOAD_MESH(PATH_MESH_ASSET_ICON_SOUND, MESH_ASSET_ICON_SOUND);
    NOZ_RELOAD_MESH(PATH_MESH_ASSET_ICON_SHADER, MESH_ASSET_ICON_SHADER);
    NOZ_RELOAD_MESH(PATH_MESH_ASSET_ICON_FONT, MESH_ASSET_ICON_FONT);

    // @Texture
    NOZ_RELOAD_TEXTURE(PATH_TEXTURE_PALETTE, TEXTURE_PALETTE);

    // @Font
    NOZ_RELOAD_FONT(PATH_FONT_SEGUISB, FONT_SEGUISB);

    // @Shader
    NOZ_RELOAD_SHADER(PATH_SHADER_VFX, SHADER_VFX);
    NOZ_RELOAD_SHADER(PATH_SHADER_UI_VIGNETTE, SHADER_UI_VIGNETTE);
    NOZ_RELOAD_SHADER(PATH_SHADER_UI, SHADER_UI);
    NOZ_RELOAD_SHADER(PATH_SHADER_TEXT, SHADER_TEXT);
    NOZ_RELOAD_SHADER(PATH_SHADER_LIT, SHADER_LIT);
    NOZ_RELOAD_SHADER(PATH_SHADER_SOLID, SHADER_SOLID);
}

#endif // NOZ_EDITOR
