//
// Auto-generated asset header - DO NOT EDIT MANUALLY
// Generated by NoZ Game Engine Asset Importer
//

#pragma once

#include <noz/core_assets.h>

// @Mesh
extern Mesh* MESH_ASSET_ICON_VFX;
extern Mesh* MESH_ASSET_ICON_SOUND;
extern Mesh* MESH_ASSET_ICON_SHADER;
extern Mesh* MESH_ASSET_ICON_FONT;

// @Texture
extern Texture* TEXTURE_PALETTE;
extern Texture* TEXTURE_FX;

// @Font
extern Font* FONT_SEGUISB;

// @Shader
extern Shader* SHADER_VFX;
extern Shader* SHADER_UI_VIGNETTE;
extern Shader* SHADER_UI;
extern Shader* SHADER_TEXT;
extern Shader* SHADER_LIT;
extern Shader* SHADER_SOLID;

// @name
extern const Name* NAME_VFX;
extern const Name* NAME_A;
extern const Name* NAME_E;
extern const Name* NAME_M;
extern const Name* NAME_B;
extern const Name* NAME_R;
extern const Name* NAME_NEW;
extern const Name* NAME_EDIT;
extern const Name* NAME_N;
extern const Name* NAME_S;
extern const Name* NAME_BUILD;
extern const Name* NAME_RENAME;
extern const Name* NAME_SAVE;
extern const Name* NAME_MESH;
extern const Name* NAME_SKELETON;
extern const Name* NAME_ANIMATION;


extern bool LoadAssets(Allocator* allocator);
extern void UnloadAssets();

#ifdef NOZ_EDITOR
extern void HotloadAsset(const Name* incoming_name, AssetType incoming_type);
#endif
